name: Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Pack
      uses: actions/upload-artifact@v3
      with:
        name: 'KRYPTON - Pack 36'
        path: |
          KRYPTON Preset Pack
          KRYPTON Sample Pack
          LICENSE
          !./**/*.md

